<a href="https://colab.research.google.com/github/asiimire/asiimire_patricia_2100719271/blob/main/asiimire_patricia_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Feature Selection

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importing libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2
# import matplotlib.pyplot as plt
# import seaborn as sns

In [ ]:
# load the dataset
data = '/content/drive/MyDrive/Colab Notebooks/heart.csv'
df = pd.read_csv(data)

In [ ]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [ ]:
df.shape

(303, 14)

Preparing the data

In [ ]:
data = df.values
X = data[:,0:8]
Y = data[:,8]

# Filter method

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [ ]:
# feature extraction
chi_best = SelectKBest(score_func=chi2, k=4)
k_best = chi_best.fit(X, Y)

# summarize scores
np.set_printoptions(precision=3)
print(k_best.scores_)

k_features = k_best.transform(X)
print(k_features[0:5,:])

[  4.293   1.927  51.713   3.227  14.799   0.17    0.791 151.934]
[[ 63.   3. 233. 150.]
 [ 37.   2. 250. 187.]
 [ 41.   1. 204. 172.]
 [ 56.   1. 236. 178.]
 [ 57.   0. 354. 163.]]


# Wrapper Method
Recursive Feature Elimination

In [34]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [38]:
# feature extraction

# Define the model
model_lr = LogisticRegression()

# Perform RFE to select top features
recur_fe = RFE(estimator=model_lr, n_features_to_select=3)  # Select 3 features

# Fit RFE
feature = recur_fe.fit(X, Y)  # Ensure 'X' is your feature set and 'y' is your target variable

# Print the results
print("Number of Features: %s" % (feature.n_features_))
print("Selected Features are: %s" % (feature.support_))
print("Feature Ranking: %s" % (feature.ranking_))


Number of Features: 3
Selected Features are: [False  True  True False False  True False False]
Feature Ranking: [3 1 1 4 5 1 6 2]


# Embedded Method
Ridge regression/ L2 regularization

In [39]:
from sklearn.linear_model import Ridge

In [40]:
# alpha impacts the magnitude of the range of the coefficients from 0 to infinity
ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(X, Y)

Ridge()

In [43]:
def print_coefs(coef, names=None, sort=False):
    if names is None:
        names = ["X%s" % x for x in range(len(coef))]

    lst = zip(coef, names)

    if sort:
        lst = sorted(lst, key=lambda x: -np.abs(x[0]))

    return " + ".join("%s * %s" % (round(coef_i, 3), name) for coef_i, name in lst)

# Example usage:
# Assuming ridge_reg is your trained Ridge regression model and coef_ are the coefficients
print('Ridge model: ', print_coefs(ridge_reg.coef_))

# negative coefficients dont contribute much to the columns
# we select features with higher positive values


Ridge model:  -0.004 * X0 + 0.119 * X1 + -0.138 * X2 + 0.002 * X3 + 0.001 * X4 + 0.05 * X5 + -0.021 * X6 + -0.006 * X7


# Advantages of feature selection
filter method


*   independent of classifier
*   fast and scalable
*   better computation complexity

Wrapper method


*   model is feature independent
*   minimizes computational cost
*   interacts with the classifier







